### ISSUE TITLE
Unexpected conversion of ConfigMap data keys to camel case

### ISSUE THREAD

**Issue by anadale** [tintoy/dotnet-kube-client#102]
Due to the default usage of `CamelCaseContractResolver` for JSON serialization some ConfigMap/Secret keys are incorrectly converted to Camel case. For example, key `DB_NAME` is converted to `dB_NAME` leading to the problems with consumers that are case sensitive.

**Comment by tintoy** [comment]
Thanks for reporting this - should be an easy fix :)

**Comment by tintoy** [comment]
Once this build is finished, would you mind installing its packages (version `2.3.3-develop0001`) from the dev package feed (https://www.myget.org/F/dotnet-kube-client/api/v3/index.json) and let me know that this fixes the problem for you? If so I can publish a release this afternoon.

https://travis-ci.org/tintoy/dotnet-kube-client/builds/593254678

**Comment by anadale** [comment]
Will do tomorrow morning, thank you.

Установить Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Adam Friedman <notifications@github.com>
Отправлено: Friday, October 4, 2019 12:20:19 AM
Кому: tintoy/dotnet-kube-client <dotnet-kube-client@noreply.github.com>
Копия: Григорий Никонов <gregory@nickonov.ru>; Author <author@noreply.github.com>
Тема: Re: [tintoy/dotnet-kube-client] Unexpected conversion of ConfigMap data keys to camel case (#102)


Once this build is finished, would you mind installing its packages (version 2.3.3-develop0001) from the dev package feed (https://www.myget.org/F/dotnet-kube-client/api/v3/index.json) and let me know that this fixes the problem for you? If so I can publish a release this afternoon.

https://travis-ci.org/tintoy/dotnet-kube-client/builds/593254678

**Comment by anadale** [comment]
No, it still doesn't work. I think the problem is in `KubeResourceClient.SerializerSettings` method - default `ContractResolver` is set to `CamelCasePropertyNamesContractResolver`, and it incorrectly converts capitalized strings.

**Comment by tintoy** [comment]
Hmm - ok, I may need to try building a custom contract resolver (since that overrides the naming strategy).

**Comment by tintoy** [comment]
Ok, I've fixed it (and added tests to verify that casing of keys is preserved). Sorry about that :)

https://travis-ci.org/tintoy/dotnet-kube-client/builds/593479104

**Comment by anadale** [comment]
Yes, it works now. Can you, please, publish a release version to NuGet? Thank you!

**Comment by tintoy** [comment]
Sure thing - will get that into master shortly (which will kick off the release process)

**Comment by felixfbecker** [comment]
I think this can be closed?
