### ISSUE TITLE
Create NetworkPolicy

### ISSUE THREAD

**Issue by marceloaguiar** [tintoy/dotnet-kube-client#115]
Hi, 

I'm try create a NetworkPolicy with below method, but return KubeClient.KubeApiException: 'UnsupportedMediaType: 415: Unsupported Media Type'

client.Dynamic().Apply<KubeClient.Models.NetworkPolicyV1>() 

What is the correct way to do this?

Thanks

**Comment by felixfbecker** [comment]
Sounds like your Kubernetes Server version is too old to support server-side apply. Which version are you running?

**Comment by felixfbecker** [comment]
If you just want to _create_ a resource you can use `Create()`

**Comment by marceloaguiar** [comment]
My Kubernetes version is 1.14; 
Create method of which class?

**Comment by felixfbecker** [comment]
I see `Create()` is not implemented for `DynamicClient`. You'd need to update your Kubernetes server then.

**Comment by marceloaguiar** [comment]
Unfortunately I'm using AWS EKS, so I can't upgrade the version, the last one available at this time is 1.14;

Do you know if are there plans to implement specific class for NetworkPolicy?

**Comment by tintoy** [comment]
Hi - it’s not particularly hard to do, it’s just that the dynamic client requirements were mostly driven by PSKublectl (which didn’t need Create support). I’ll see if I can have a go at that tomorrow morning.

**Comment by tintoy** [comment]
Sorry, didn’t get time over the weekend but will look into it tomorrow morning.

**Comment by marceloaguiar** [comment]
Thanks, this enhancement will be very usefull

**Comment by tintoy** [comment]
Hi - I've added `Create` support to the dynamic resource client, as well as adding a strongly-typed resource client for `NetworkPolicy` resources.

Can you give v2.3.9 a try and let me know if it works for you?

**Comment by marceloaguiar** [comment]
For now, works perfectly. Thanks
