### ISSUE TITLE
Telepresence support

### ISSUE THREAD

**Issue by jonstelly** [tintoy/dotnet-kube-client#118]
[Telepresence](https://www.telepresence.io/) can be used to develop against a kubernetes cluster.  One of the ways you can use telepresence is to run a docker container locally that has traffic and dns to/from the kubernetes cluster proxied via telepresence.  In this mode, volumes get mounted under a `TELEPRESENCE_ROOT` path that's set as an environment variable as mentioned [here](https://www.telepresence.io/howto/volumes).  This is also where Kubernetes secrets get mounted.

To support this, I made a rough pass at tweaking the `FromPodServiceAccount()` method to look for that environment variable: [changes](https://github.com/tintoy/dotnet-kube-client/compare/develop...Kymeric:feature/telepresence?expand=1)

Any thoughts here?  I think it'll be safer to put this behind a parameter, something like:

```c#
KubeClientOptions FromPodServiceAccount(bool checkForTelepresence = false)
```

If that seems agreeable I can clean this up and create a PR, but wanted to get thoughts on naming/pattern if you had any.

**Comment by tintoy** [comment]
Hi - how about if we make this non-Telepresence-specific? Could have an overload that lets them pass the base path for secrets?

**Comment by jonstelly** [comment]
I changed it around like you suggested.  I also exposed some strings as constants off of `KubeClientOptions` to make it easier for callers to support telepresence and maybe some other one-off scenarios.

**Comment by tintoy** [comment]
Thanks! I’ll give this a look first thing tomorrow :)
