### ISSUE TITLE
How is the ApiEndPoint configured for this parameter

### ISSUE THREAD

**Issue by 344089386** [tintoy/dotnet-kube-client#123]
I am not using native Kubernetes, but I have been reporting errors. I suspect there is something wrong with this address configuration. Could you give me some advice

**Comment by jonstelly** [comment]
If you're talking about the `KubeClientOptions.ApiEndPoint` property, that should be the Kubernetes API Endpoint which is different depending on which Kubernetes implementation you're deploying and how it's configured.

For k3s, port 6443 is the default, so whichever k3s node is your master the URL is `https://k3s-master:6443`.  On Azure AKS you'll see an api endpoint like: `https://name-something.something.region.azmk8s.io:443`  I think microk8s uses port 16443 by default.

Is that what you're looking for?

**Comment by 344089386** [comment]
I decided to use native Kubernetes to avoid some mistakes.
thank you.

**Comment by 344089386** [comment]
The Kubernetes I'm using now, the ApiEndPoint is configured with an external 6443 address, and the AccessToken is a token generated by using these three lines of command:
kubectl create serviceaccount dashboard-admin -n kube-system
kubectl create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=kube-system:dashboard-admin
kubectl describe secrets -n kube-system $(kubectl -n kube-system get secret | awk '/dashboard-admin/{print $1}')
![image](https://user-images.githubusercontent.com/22017199/87774177-cb31c280-c856-11ea-8f25-3ec5466b1392.png)

Still report an error:
![image](https://user-images.githubusercontent.com/22017199/87774265-e3a1dd00-c856-11ea-9bbc-6c2b3d821d0f.png)

Please take a look at it for me, thank you

**Comment by tintoy** [comment]
Are you able to connect to that host and port using `curl` or `telnet`? That error normally means that the port is not accessible at all...

**Comment by 344089386** [comment]
@tintoy 
thank you
That's exactly what you said, HTTP mapping is wrong, I'm mapping to node node, I should be mapping to master
