### ISSUE TITLE
Detect current Pod namespace

### ISSUE THREAD

**Issue by wasabii** [tintoy/dotnet-kube-client#137]
It looks like using KubeClient.Extensions.Configuration requires the kubeNamespace to be passed, or it defaults down to "default". Instead, it should attempt to read the namespace from /var/run/secrets/kubernetes.io/serviceaccount/namespace. Looks like this should go into `CreateFromPodServiceAccount`.

**Comment by tintoy** [comment]
Good idea!

I’ll add that in sometime this weekend 🙂

**Comment by tintoy** [comment]
Hi - I haven’t forgot about this, work’s just a little busy at the moment. I hope to have time to add this in tonight 🙂

**Comment by tintoy** [comment]
Published [v2.4.6](https://app.travis-ci.com/github/tintoy/dotnet-kube-client/builds/237952581) 🙂 

(may take a while to become visible on NuGet; I think their indexing process is asynchronous)

**Comment by tintoy** [comment]
(sorry for the long delay, I thought this had already been published in the previous release!)
