### ISSUE TITLE
Cannot get output when using ExecAndConnect

### ISSUE THREAD

**Issue by zxyao145** [tintoy/dotnet-kube-client#154]
Hello, I'm trying to use ExecAndConnect to interact with Pod, but I can't get the 'remoteStdOut' response. And if I try to use the example (https://github.com/tintoy/dotnet-kube-client/blob/develop/samples/noob-exec/Program.cs), it works.

What should I do?

```c#
   var multiplexer = await client.PodsV1().ExecAndConnect(
        podName: info.PodName,
        container: info.ContainerName,
        command: "/bin/sh",
        stdin: true,
        stdout: true,
        stderr: false,
        tty: true
    );


    Stream remoteStdIn = multiplexer.GetStdIn();
    Stream remoteStdOut = multiplexer.GetStdOut();

    _ = Task.Run(async () =>
    {
        var buffer = new byte[1024 * 4];
        var readCount = await remoteStdOut.ReadAsync(buffer);
        Console.WriteLine(Encoding.UTF8.GetString(buffer.Take(readCount).ToArray()));
    });

    _ = Task.Run(async () =>
    {
        for (int i = 0; i < 100; i++)
        {
            if (i % 2 == 0)
            {
                await remoteStdIn.WriteAsync(Encoding.UTF8.GetBytes("ls"));
            }
            else
            {
                await remoteStdIn.WriteAsync(Encoding.UTF8.GetBytes("pwd"));
            }

            await Task.Delay(500);
        }

        Console.WriteLine("finished");
    });

    Console.Read();

    remoteStdIn.Dispose();
    remoteStdOut.Dispose();
    multiplexer.Dispose();
```
![image](https://user-images.githubusercontent.com/24973084/210089531-e742ec02-c90e-410c-9548-c994c3444d0c.png)

**Comment by tintoy** [comment]
Hi 🙂

I could be wrong, but I think the (synchronous) `Console.Read` call is blocking and that might be clogging up your event- pump? Async stuff like this is a little tricky in console apps unfortunately.

Maybe try `await multiplexer.WhenConnectionClosed` and have your command task send a`WriteLine(“exit”)` after the `WriteLine(“ls”)` instead…

For a fancier version of this idea maybe check out https://github.com/davidfowl/TriviaR/blob/main/TriviaR.Console/AsyncConsole.cs although it may be overkill for your use-case…

**Comment by zxyao145** [comment]
Thank you! I probably understand what's going on. I try to using it in aspnet core, and it can output values, but the output value always is always the input content. For example, if I enter "ls", it always returns "ls", and there is no result of executing the command "ls". Can you help me explain why? Thanks again!

**Comment by zxyao145** [comment]
> Thank you! I probably understand what's going on. I try to using it in aspnet core, and it can output values, but the output value always is always the input content. For example, if I enter "ls", it always returns "ls", and there is no result of executing the command "ls". Can you help me explain why? Thanks again!

Hello, I know what happened. For each line, a new line character "\n" should be added. Happy New Year!
