### ISSUE TITLE
Watch request fails with InvalidOperationException

### ISSUE THREAD

**Issue by kick2nick** [tintoy/dotnet-kube-client#163]
There is a log call introduced in https://github.com/tintoy/dotnet-kube-client/commit/8cda77d93971eba77c3817c5a12f169442652f87 that uses PathAndQuery property of created request.
https://github.com/tintoy/dotnet-kube-client/blob/1e08492a6da6ce484ae4b9e5e2ec66a38fe802da/src/KubeClient/ResourceClients/KubeResourceClient.cs#L596-L598
But HttpRequest created by factory is relative URI, so on attempts to call ObserveLines I'm getting exception in Observable OnError:
```Unexpected error while streaming from the Kubernetes API to \"watch v1/Endpoints 'some-service' in namespace dev\".","exceptions":["System.InvalidOperationException: This operation is not supported for a relative URI.","   at System.Uri.get_PathAndQuery()","   at KubeClient.ResourceClients.KubeResourceClient.<>c__DisplayClass30_0.<<ObserveLines>b__0>d.MoveNext()```

**Comment by tintoy** [comment]
Good catch! Thanks, I’ll get that fixed tomorrow 🙂

**Comment by tintoy** [comment]
@kick2nick - if I can get new packages published to our development package feed, would you be able to verify whether they resolve the issue for you?

**Comment by kick2nick** [comment]
Yes, I would be able

**Comment by tintoy** [comment]
Can you try [v2.5.11-develop.5](https://www.myget.org/feed/dotnet-kube-client/package/nuget/KubeClient/2.5.11-develop.5)?

**Comment by kick2nick** [comment]
Got this 😄 :
`exceptions":["System.InvalidOperationException: This operation is not supported for a relative URI.","   at System.Uri.get_Scheme()","   at System.UriBuilder.SetFieldsFromUri()","   at KubeClient.Utilities.UriHelper.SafeGetPathAndQuery(Uri uri)`

**Comment by tintoy** [comment]
Ok, that’s odd - I thought I’d tested it pretty thoroughly  but perhaps the behaviour is different in PowerShell 🤷🏻

I’ll write up some unit tests and see what’s going on (`System.Uri`‘s handling of relative URIs is surprisingly bad).

**Comment by tintoy** [comment]
Ugh, it _is_ different in PowerShell (where I did my testing). Needs to be `new UriBuilder(uri.OriginalString)`, not `new UriBuilder(uri)`.

**Comment by tintoy** [comment]
I’ll add some tests once I get to my computer; it seems there are a couple of unexpected quirks in the BCL’s handling of relative URIs 🙂

**Comment by tintoy** [comment]
Ok, can you try v[2.5.11-develop.7](https://www.myget.org/feed/dotnet-kube-client/package/nuget/KubeClient/2.5.11-develop.7)? There are a [bunch of tests](https://github.com/tintoy/dotnet-kube-client/blob/develop/test/KubeClient.Tests/UriHelperTests.cs), now, for URI handling, so I'm pretty confident it should work correctly now (I'd integration-test this myself, but I don't have a working k8s cluster at the moment!).

**Comment by kick2nick** [comment]
Tested in k8s new version, watch request works as expected.
Log entry:
`Start streaming \"GET\" request for \"/api/v1/watch/namespaces/%7BNamespace%7D/endpoints/%7BServiceName%7D\`
It has no route params, but probably it's ok for debug log)

**Comment by tintoy** [comment]
I’ll see what I can do about expanding the route parameters, but it may require an enhancement to the HTTP template library :)

**Comment by kick2nick** [comment]
It's your choice, but as far as I understand this bug impacts all watch requests in your library, so this enhancement could be part of separate PR if it need time.

**Comment by tintoy** [comment]
Definitely agree; will leave that for later, but can at least make the logging conditional on the configured log level. Will publish a release version tomorrow morningz

**Comment by kick2nick** [comment]
Cool, thank you for quick fix!

**Comment by tintoy** [comment]
BTW, I will probably remove that log statement as KubeClient’s existing request/response logging will already include that populated URI.

**Comment by tintoy** [comment]
Publishing [v2.5.12](https://github.com/tintoy/dotnet-kube-client/releases/tag/v2.5.12)...

**Comment by raman-m** [comment]
> @tintoy commented [on Oct 16](https://github.com/tintoy/dotnet-kube-client/issues/163#issuecomment-2415586901)

Did you forget to tag the release as the latest one, or is it a pre-release?

**Comment by tintoy** [comment]
Good catch! Done 🙂
