### ISSUE TITLE
Multi-targeting (netstandard2.1, net7.0, net8.0, net9.0)

### ISSUE THREAD

**Issue by tintoy** [tintoy/dotnet-kube-client#167]
Note - breaking changes in `net9.0`:

https://learn.microsoft.com/en-us/dotnet/core/compatibility/9.0

**Comment by raman-m** [comment]
Please be aware that Microsoft has not supported .NET 7 since May 2024 &rarr;
- [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

It appears that the `net7.0` target should be removed from the list.

**Comment by tintoy** [comment]
Unfortunately, I know of at least one (commercial, closed-source) project that uses dotnet-kube-client but can't be upgraded to `net8.0` yet (yes, I know, but it's not my call to make in that particular case).

`net9.0` introduces quite a few breaking changes and deprecations, BTW.

Once we have stabilised everything, then yes - my plan is to drop `net7.0`.

**Comment by tintoy** [comment]
This working is pretty much complete at this stage; no major issues have arisen from multi-targeting so far.

Any remaining work will be handled by the completion of #166.
