### ISSUE TITLE
Expose Kubernetes OpenAPI extensions as attributes on members

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#23]
To properly patch resources (like a `kubectl apply`), it is necessary to know how the fields (especially lists) in the resources are intended to be merged. This is exposed as OpenAPI extensions in `x-kubernetes-patch-strategy` and `x-kubernetes-patch-merge-key`.

- https://github.com/kubernetes/kubernetes/blob/8f4ab6fe7635983443ebef7fde5b9c8861bef5bb/api/openapi-spec/README.md#x-kubernetes-patch-strategy-and-x-kubernetes-patch-merge-key
- https://github.com/kubernetes/community/blob/72e931e1142ce47634f974cd12dae2ebf34b4472/contributors/devel/strategic-merge-patch.md

**Comment by tintoy** [comment]
Ok yeah this looks interesting! :)

I'm happy to have a go at this unless you'd like to open a PR yourself (either is fine by me).

**Comment by tintoy** [comment]
@felixfbecker can you have a look at  https://github.com/tintoy/dotnet-kube-client/commit/5092fd14faf0de6575ace26da279221c68fe533a and see if that's the information you want?

**Comment by felixfbecker** [comment]
Looks right! But would need to be actually applied from the OpenAPI schema

**Comment by tintoy** [comment]
Are you expecting to find the attribute on all properties, or will it suffice on fields that should be merged (with the default being `replace` for all others)?

If so, I'd change the attribute to something like `StrategicPatchMergeAttribute`, remove the enum, and only decorate properties with `[StrategicPatchMerge(Key="name")]` (or similar) if the field is mergeable.

The reasoning behind this is that the only time `x-kubernetes-patch-strategy` appears in the Swagger for the Kubernetes API, it has the value `merge` (i.e. never `replace`).

**Comment by tintoy** [comment]
> But would need to be actually applied from the OpenAPI schema

Yep - the Python script that generates the models would emit it :)

**Comment by felixfbecker** [comment]
Not sure, I think I would just apply it wherever the OpenAPI schema applies it

**Comment by tintoy** [comment]
Ok, I can work with that - should have it done sometime today I hope :)

**Comment by tintoy** [comment]
I think we've dealt with this one but I can't be sure - when you have a moment can you check if the API does what you want now?

**Comment by felixfbecker** [comment]
Yeah this gives all I need!
