### ISSUE TITLE
Does Travis need Mono installed?

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#30]
I see that .travis.yml sets `mono: latest` and CI spends a long time installing Mono. Is that actually needed if compilation is done with the .NET Core CLI? Can it be set to `mono: none`?

**Comment by tintoy** [comment]
GitVersion needed mono but they may support core now...

**Comment by tintoy** [comment]
Hmm - tried but no dice. Could be done with a little extra work, but configuration looks a little ugly so may wait until later to give this a try :)

**Comment by tintoy** [comment]
Will switch back to AppVeyor at some point (originally switched to Travis because AppVeyor didn't support latest .NET Core SDK) and run unversioned CI on travis (i.e. no build-time dependency on Mono).

**Comment by tintoy** [comment]
Now using gitversion as a .NET Core global tool, and mono dependency has been removed.
