### ISSUE TITLE
Support apps/v1 Deployment

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#32]
Seems like Deployment is out of beta now

**Comment by tintoy** [comment]
I think we need the latest OpenAPI document for that. I'll take a look at the official client project tomorrow morning and see if they have a copy lying around.

**Comment by tintoy** [comment]
Hi - so am I correct in assuming this is now resolved?

**Comment by felixfbecker** [comment]
Yup
