### ISSUE TITLE
Throw custom exceptions on errors 

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#33]
Currently, when the server returns a non-200 status code, we just propagate the low-level HTTPlease `HttpException`. This is a bad experience, because it does not have a very useful message:

```
Update-KubeResource : The request failed with unexpected status code 'InternalServerError'.
At /Users/felix/src/github.com/felixfbecker/PSKubectl/Tests/PSKubectl.Tests.ps1:175 char:37
+ ...      try { $result = $modified | Update-KubeResource -Verbose } catch ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Update-KubeResource], HttpRequestException`1
+ FullyQualifiedErrorId : HTTPlease.HttpRequestException`1[[KubeClient.Models.StatusV1, KubeClient, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null]],Kubectl.Cmdlets.UpdateKubeResourceCmdlet
```

Kubernetes returns structured JSON information with errors (`StatusV1`, that is available on `exception.Response`). We should catch errors and rethrow a special `KubeAPIException` that makes use of the know strongly-typed metadata, i.e. use `Status.Reason` and `Status.Message` to construct the exception message (in the example above, that would have been `Testing value /spec/template/spec/containers/0/env/1/name failed`, which is a lot more specific). The rest of the status that's useful (`Causes`, `Details` etc) can then be available on a `Status` property on the exception. `InnerException` would be the raw HTTP exception.

**Comment by tintoy** [comment]
Good idea! Have been meaning to do this - will look into it in an hour or so.

**Comment by tintoy** [comment]
We have this, BTW, it's just not being used consistently:

https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/KubeClientException.cs

**Comment by tintoy** [comment]
I reckon https://github.com/tintoy/dotnet-kube-client/commit/d13797a39a2ab1b2e0630cb691494fedba460f61 is a good start :)

Any feedback?

**Comment by felixfbecker** [comment]
Oh, I didn't realise that this already existed.
I am still getting `HttpRequestException` with `DynamicClient.Patch()` though...

**Comment by tintoy** [comment]
Interesting - you mean the non-generic one?

https://github.com/tintoy/dotnet-kube-client/blob/feature/dynamic-client/src/KubeClient/ResourceClients/DynamicResourceClient.cs#L251-L266

**Comment by tintoy** [comment]
Hi sorry for the silence on this end - as usual, work and life get in the way. Will be spending some more time on this tonight to add tests that verify error handling. Let me know if you have opinions or other input :)

**Comment by tintoy** [comment]
@felixfbecker - what do you reckon, is this test good enough?

https://github.com/tintoy/dotnet-kube-client/commit/d19dae0155a7a8006a6e7e92713b3ab1196e989a

PS. As a result of writing this test, I found and fixed the problem where you'd still see `HttpRequestException<TResponse>` instead of `KubeClientException`.

I'll try to get a proper release together before the end of this weekend :)

**Comment by tintoy** [comment]
This has been resolved as of the most recent release. Feel free to reopen if you hit any non-KubeClient exceptions that you think shouldn't be exposed to callers :)
