### ISSUE TITLE
Model types are missing API Group in their API Versions

### ISSUE THREAD

**Issue by bastianeicher** [tintoy/dotnet-kube-client#38]
Many of the auto-generated model types are missing the appropriate API Group in their API Versions.

For example `DeploymentV1` is annotated with:
```csharp
[KubeObject("Deployment", "v1")]
```
but this actually should be:
```csharp
[KubeObject("Deployment", "apps/v1")]
```

This results in objects that are `new`ed up and then sent to the API being rejected because they contain the wrong value in the `apiVersion` field.

**Comment by tintoy** [comment]
Hmm, I thought we'd fixed this a while back but perhaps the issue has reared its ugly head again (we made a bunch of changes recently to support dynamic resource clients). I'll have a look this morning and get that sorted out.

**Comment by tintoy** [comment]
Ok, I think it should be correct again now (see PR #39)? :grin:

**Comment by bastianeicher** [comment]
Awesome, thanks. :)

**Comment by bastianeicher** [comment]
Seems fine in the latest release.
