### ISSUE TITLE
Deserialisation from deployment yaml

### ISSUE THREAD

**Issue by bobcnz** [tintoy/dotnet-kube-client#41]
I noticed when using this project to read in a static deployment yaml file, that a there is a missing yaml member alias attribute on src/KubeClient/Models/KubeResourceV1.cs

[YamlMember(Alias = "metadata")]

Without that it expects metadata to be Metadata

**Comment by tintoy** [comment]
Fixed in latest release. Feel free to reopen if you still have problems :)
