### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bastianeicher** [tintoy/dotnet-kube-client#45]
Hi @tintoy,

there are quite a few fixes in the trunk by now, #35, #39 and #44, that I'd love deploy.
Could you perhaps publish a new release of the lib on NuGet?

Regards
Bastian

**Comment by tintoy** [comment]
Hi! Thanks for the reminder, doing it now :)

**Comment by tintoy** [comment]
Building: https://travis-ci.org/tintoy/dotnet-kube-client/builds/455415750

**Comment by tintoy** [comment]
Packages published (v2.1.8). Do you have time to try them out to see if they work for you?

**Comment by bastianeicher** [comment]
Awesome, thanks. :)
nuget.org is still indexing the new version. Will give it a spin as soon as that's done and post here.

**Comment by bastianeicher** [comment]
I see you just published 2.1.9 as well. Just curious: what changed there?

**Comment by tintoy** [comment]
Just fixed the build script - symbolsource is broken :)

**Comment by bastianeicher** [comment]
Looking good so far, but I just noticed that #43 isn't merged yet. Any chance of sneaking that in?

**Comment by tintoy** [comment]
https://travis-ci.org/tintoy/dotnet-kube-client/builds/455452803

**Comment by bastianeicher** [comment]
Perfect. 👍 I'll be updating our assets with this.

On a slight tangent: Have you had an opportunity to look at #42? Not urgent, just a nice-to-have.
