### ISSUE TITLE
StatefulSet ResourceClient

### ISSUE THREAD

**Issue by mikecowgill** [tintoy/dotnet-kube-client#47]
I'm really liking the structure of this project over the "official" k8s dotnet client. Today I decided to port the a project from the other client to this but ran into a small issue. I doesn't seem there is a StatefulSet ResourceClient. From what I understand, you've hand coded those rather than rely on swagger (which is great).

I can create the StatefulSet resource client and submit a PR if it's just something you haven't got around to. Or am I missing something? Thanks!

**Comment by tintoy** [comment]
Hi! Yep, just haven't got to it yet, and always happy to take PRs :)

Feel free to hit me up for info if anything is unclear about how to add a new resource client (maybe copy from DeploymentClientV1)?

**Comment by mikecowgill** [comment]
Sounds good, yeah I figured I'd just copy from an existing ResourceClient. For the heck of it I tried using the DynamicResourceClient but couldn't get it working for returning the List of StatefulSets. Doesn't look like it implements a LabelSelector though, which I needed.

Should be quick to write the StatefulSetClientV1 based on DeploymentClientV1. I'll try to knock it out today.

**Comment by tintoy** [comment]
Feel free to reopen if this doesn't do what you need, BTW :)
