### ISSUE TITLE
The request failed with unexpected status code 'Forbidden' when connecting to AKS (dev spaces)

### ISSUE THREAD

**Issue by ossentoo** [tintoy/dotnet-kube-client#49]
hi,

- I'm running VS 2017 15.9.3 Preview 1.0.
- I'm have installed the VS Kubernetes Tools.
- I've deployed an ASPnet core 2.2 mvc app.

I've seen this issue: tintoy/dotnet-kube-client#20

However, my issue is slightly different. I create an AKS, and get Azure dev spaces
 installed.  I then deploy a a mvc web project to it using VS 2017.  

This is the code I'm using to read my secrets with kube-client.

```csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .ConfigureAppConfiguration(
                    configuration => GetConfigurationBuilder(configuration)
                )
                .UseStartup<Startup>()
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Program).GetTypeInfo().Assembly.FullName); // beware of this

        private static IConfigurationBuilder GetConfigurationBuilder(IConfigurationBuilder configuration)
        {
            if (Hosted.ByKubernetes)
            {
                _isConfiguredKubernetes = true;
                return configuration.AddKubeSecret(secretName: DbConnectionString,
                    clientOptions: KubeClientOptions.FromPodServiceAccount(),
                    kubeNamespace: "default",
                    reloadOnChange: true
                );
            }

            _isConfiguredKubernetes = false;

            return configuration;
        }
```

this code runs.  however, the exception then occurs on this line:

```csharp
            var host = CreateWebHostBuilder(args).Build();
```

Here's the exception log:

```
Exception thrown: 'HTTPlease.HttpRequestException`1' in System.Private.CoreLib.dll: 'The request failed with unexpected status code 'Forbidden'.'
Stack trace:
 >   at HTTPlease.FormatterResponseExtensions.<ReadContentAsAsync>d__15`2.MoveNext()
 >   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 >   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 >   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
 >   at KubeClient.ResourceClients.KubeResourceClient.<GetSingleResource>d__18`1.MoveNext()
 >   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 >   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 >   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 >   at KubeClient.ResourceClients.SecretClientV1.<Get>d__1.MoveNext()
 >   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 >   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 >   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 >   at KubeClient.Extensions.Configuration.SecretConfigurationProvider.Load()
 >   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
 >   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
 >   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
 >   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
 >   at Application.Web.Program.Main(String[] args) in /src/application.web/Program.cs:line 25
```

I have previously created a secret on the AKS with the following command:

`kubectl create secret generic application-web-appsettings "--from-literal=DBConnectionString='sql connection string'" -o json`

I have verified that the secret exists

**Comment by tintoy** [comment]
Which namespace does the pod live in, BTW? I thought the idea with dev spaces was to use different namespaces in the same cluster, in which case you may have better luck dropping the secret into the same namespace as the pod (or granting broader permissions to the pod service account).

**Comment by ossentoo** [comment]
Pod is in the Default namespace

**Comment by tintoy** [comment]
Have you checked what permissions the pod service account has?

**Comment by tintoy** [comment]
(I think `kubectl get clusterrolebindings` will show you the info you need, although it's a been a while since I've worked with K8s RBAC, so I could be wrong)

**Comment by ossentoo** [comment]
ah ok - thanks. I tried that and received a long list of permissions.  Not sure what I'm looking for.

NAME                                                               AGE
addon-http-application-routing-nginx-ingress-clusterrole-binding   10h
addon-http-application-routing-viewer                              10h
azds:tiller-deploy                                                 10h
cluster-admin                                                      10h
heapster                                                           10h
kubernetes-dashboard                                               8h
metrics-server:system:auth-delegator                               10h
system:aws-cloud-provider                                          10h
system:basic-user                                                  10h
system:controller:attachdetach-controller                          10h
system:controller:certificate-controller                           10h
system:controller:clusterrole-aggregation-controller               10h
system:controller:cronjob-controller                               10h
system:controller:daemon-set-controller                            10h
system:controller:deployment-controller                            10h
system:controller:disruption-controller                            10h
system:controller:endpoint-controller                              10h
system:controller:expand-controller                                10h
system:controller:generic-garbage-collector                        10h
system:controller:horizontal-pod-autoscaler                        10h
system:controller:job-controller                                   10h
system:controller:namespace-controller                             10h
system:controller:node-controller                                  10h
system:controller:persistent-volume-binder                         10h
system:controller:pod-garbage-collector                            10h
system:controller:pv-protection-controller                         10h
system:controller:pvc-protection-controller                        10h
system:controller:replicaset-controller                            10h
system:controller:replication-controller                           10h
system:controller:resourcequota-controller                         10h
system:controller:route-controller                                 10h
system:controller:service-account-controller                       10h
system:controller:service-controller                               10h
system:controller:statefulset-controller                           10h
system:controller:ttl-controller                                   10h
system:discovery                                                   10h
system:kube-controller-manager                                     10h
system:kube-dns                                                    10h
system:kube-proxy                                                  10h
system:kube-scheduler                                              10h
system:metrics-server                                              10h
system:node                                                        10h
system:node-proxier                                                10h
system:volume-scheduler                                            10h

**Comment by tintoy** [comment]
The other thing you can try is to explicitly try to retrieve the secret using `KubeApiClient`; somewhere inside the exception tree, there will be an `HttpRequestException<StatusV1>`, and you can examine its properties to get more information about the response from the K8s API.

**Comment by tintoy** [comment]
Yeah, sorry, I don't actually have a K8s cluster at the moment, so I can't really try this stuff out myself :-(

Maybe try the suggestion above and look at the exact error message from the K8s API which should tell you what was forbidden and why?

**Comment by ossentoo** [comment]
Finally, i got it.  I had problems with the dev space.  Some some reason it stopped running my code and I had to rebuild it.  Anyway, here's the error:

I think you are right. 

`secrets "DBConnectionString" is forbidden: User "system:serviceaccount:default:default" cannot get secrets in the namespace "default"
`

**Comment by ossentoo** [comment]
I just want to make sure I'm querying for the right thing:

![image](https://user-images.githubusercontent.com/7569380/49974404-ef1d7b80-ff30-11e8-9b1f-897f8b5613ac.png)

Should I be querying for secret name (as shown it ends in appsettings), as shown?  

I'm querying for DBConnectionString at the moment.

Hope I'm not making a very basic error myself.

Here;s the call I am making:

`                return configuration.AddKubeSecret(secretName: DbConnectionString,
                    clientOptions: KubeClientOptions.FromPodServiceAccount(),
                    kubeNamespace: "default",
                    reloadOnChange: true`

where DbConnectionString = "DBConnectionString"

**Comment by tintoy** [comment]
Ah, no - `secretName` refers to the name of the `SecretV1` resource (`xxxxx-appsettings`), not a key inside it. The keys inside it become keys in the `IConfiguration` (that can then be bound to options). So you can either retrieve the connection string in your app using:

```csharp
string connectionString = Configuration["DBConnectionString"];
```

Or bind it to options using:


```csharp
class MyOptions
{
    public string DBConnectionString { get; set; }
}

services.Configure<MyOptions>(Configuration);
```

**Comment by ossentoo** [comment]
thanks for this.  I think as you describe the issue is permissions related.
