### ISSUE TITLE
Want to contribute to the official client?

### ISSUE THREAD

**Issue by brendandburns** [tintoy/dotnet-kube-client#6]
Hello,
There is an official dotnet client here:

https://github.com/kubernetes-client/csharp

We'd love to have your help there if you wanted to combine forces!

Thanks
Brendan

**Comment by tintoy** [comment]
Hi! I looked for an official client, but I didn't realise there was a separate repo for clients! Yeah, sure, no sense in doubling up on effort; I'd be happy to pitch in with yours :)

**Comment by tintoy** [comment]
I wish I'd seen your client before I went to all that effort getting WebSockets / interleaved streams working; but I'm glad to see the design is basically the same (so I was probably on the right track).

I'll have a look over the official client next week and see if there's anything in mine that might be a useful addition :)

**Comment by brendandburns** [comment]
I want to steal your certificate authority+ web socket code.

Your comment on the dotnet core issue is how I found the repo!

Many thanks look forward to working together!

--brendan

________________________________

**Comment by tintoy** [comment]
Same here! :)

**Comment by tintoy** [comment]
Thanks, closing this issue now that the official client is GA!

I've also updated the README to indicate this fact :)
