### ISSUE TITLE
Support server-side apply

### ISSUE THREAD

**Issue by felixfbecker** [tintoy/dotnet-kube-client#63]
This feature is the most exciting to me about Kubernetes in a long time:

https://github.com/kubernetes/enhancements/issues/555
https://github.com/kubernetes/kubernetes/pull/72947

Soon to be released in Alpha.

This will make it possible for PSKubectl to implement `kubectl apply` without having to reverse-engineer the merge algorithm on the client.

**Comment by felixfbecker** [comment]
This has been available behind a feature flag since 1.14 (latest version is 1.15.1) by launching with `--feature-gates=ServerSideApply=true` (works in Minikube).
Docs are here: https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

API-wise, I would imagine an `Apply()` method on `DynamicClient` which takes a `KubeResource` that gets serialized to YAML or JSON before sending, and an `ApplyYaml()` method that takes a raw YAML string.

The request simply is just like the PATCH request but with `Content-Type: application/apply-patch+yaml`.

Would love to try this and ship support in PSKubectl!

**Comment by felixfbecker** [comment]
The method also needs to send a required query parameter `fieldManager` (string). It can also be send for other update requests but is only required for apply.

**Comment by felixfbecker** [comment]
I tried to make this work but couldn't make it work as I'm not that familiar with HTTPlease (how to send string content and add query parameters)

**Comment by felixfbecker** [comment]
Also related: Currently the new field `metadata.managedFields` does not exist yet in the model classes.

**Comment by tintoy** [comment]
Hi - I’ll have a look at this first thing tomorrow! Sorry, today’s been crazy and I need some sleep 🙂

**Comment by tintoy** [comment]
BTW, glanced at docs for managedFields, and since it’s alpha I was thinking of making the property a `JArray` or adding one of those catch-all serialisation properties to handle members that the model might not yet cover. Any opinions either way? Otherwise I might hand-code that model for now because it’s been a while since I tried to pull in new Swagger and each time they seem to change something fairly innocuous-**seeming** that nevertheless breaks the generator script 🤣

**Comment by tintoy** [comment]
(I guess it depends if you want make it easy for you to inspect the contents of this property or simply treat it as an opaque value that gets round-tripped :)

**Comment by felixfbecker** [comment]
A JArray wouldn't be very convenient in PowerShell so I think it would either be natively supported or not at all. `managedFields` not that important after all and cannot be modified. It is `managedFields` is a dictionary so I think when it's not enabled it could just be `null` or empty. The type didn't look that easy to I'd recommend looking at the JSON schema

**Comment by tintoy** [comment]
See [JsonExtensionDataAttribute](https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm)

**Comment by tintoy** [comment]
Ok, so neither the OpenAPI spec nor the API docus actually contain any useful information about `managedFields`. So my vote is for something round-trippable but free-form (since it's unclear what format the returned data will actually be in).

My vote is to use the `[JsonExtensionData]` attribute, since this will allow round-tripping of required values, and is future-proof (it does not preclude an actual `ManagedFields` property being added to the model later, because `[JsonExtensionData]` is only used for `JToken`s that cannot be matched to a specific model property). I can add that pretty easily if it will still help you (as far as I can tell, you don't need to specifically inspect that property to use server-side apply, only to ensure that you round-trip any value in there that K8s supplies to you).

**Comment by tintoy** [comment]
As for the new request methods, I can add those this afternoon if you have a system where you can test them :)

**Comment by felixfbecker** [comment]
I found it in JSON schema here: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/garethr/kubernetes-json-schema%24+managedFields+timeout:60s+f:%5Emaster/

but we can just punt on that field for now. What's important is the API request methods, with the _URL query parameter_ `fieldManager`.
I have local WIP code for PSKubectl and minikube with server-side apply running :)

**Comment by tintoy** [comment]
Awesome! Ok, I’ll add those methods tomorrow :)

**Comment by tintoy** [comment]
Looks to me like it also supports `Content-Type: application/apply-patch+json`. Any objections to using this instead of YAML? The YAML serialiser doesn't seem to be as reliable as the JSON one so it would probably be simpler to stick to a single format,,,

**Comment by felixfbecker** [comment]
Yeah JSON should work, even with `Content-Type: application/apply-patch+yaml`, because JSON is a subset of YAML.

**Comment by tintoy** [comment]
Hopefully that's a good starting point :)

BTW, there's a [`Yaml`](https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/Models/Yaml.cs) class that can be used to convert YAML into JSON (a `JToken`, specifically).

**Comment by felixfbecker** [comment]
Awesome! I see the current method only takes a full `KubeResourceV1`. What I would like to allow is to pass in raw YAML or PSCustomObjects into PSKubectl. What do you think is the best to solve that? I could map them into KubeResources, but that would have the problems we chatted about in #28.
I think the easiest solution would be for the client to accept a raw YAML string (the `ApplyYaml()` API) and for PSKubectl to do the serialization of PSCustomObjects.

**Comment by tintoy** [comment]
Implementing ApplyYaml will be pretty easy BTW, will do it first thing tomorrow (sorry, it’s 10:30pm here and I’ve been up since 4am!)

**Comment by tintoy** [comment]
Ok - that should do the trick :)

**Comment by felixfbecker** [comment]
I tested it with Postman and `application/apply-patch+json` returns 415 Unsupported Media Type, while `application/apply-patch+yaml` works. Where did you see that it supports `application/apply-patch+json`?

**Comment by felixfbecker** [comment]
Not sure why it fails for me with the client though with a 415, because I am using `ApplyYaml`, which should send `application/apply-patch+yaml`...
I tried setting `LogHeaders = true` to confirm but I don't see any headers logged (only the body)

**Comment by tintoy** [comment]
Weird - will try writing an integration test to verify.

**Comment by tintoy** [comment]
Hah, ok it's a bug in HTTPlease. When you supply `HttpContent` instead of a model to serialise, it doesn't use the media type you specify when you call `PatchAsync`. I'll fix that later, but for now will just explicitly override the media type :)

**Comment by tintoy** [comment]
Ok, both should be working now :)
