### ISSUE TITLE
How to manage Ingress ?

### ISSUE THREAD

**Issue by MichaelJCompton** [tintoy/dotnet-kube-client#75]
I can find `IngressSpecV1Beta1`, but not an Ingress class that inherits from `KubeResourceV1 ` or anything off `KubeApiClient` to create and manage ingress. 

Is it not supported, or am I missing the magic?

**Comment by tintoy** [comment]
Hmm, the models are generated from the Swagger / OpenAPI document (see `src/swagger`) so if the API exists there should be models for it.

I’ll have a look at the model class generator script  first thing tomorrow and see what’s going on. Sorry about that :-/

**Comment by tintoy** [comment]
Hmm - looks like the model-generation script was too aggressive in filtering out duplicate definitions and somehow the `IngressV1Beta1` and `IngressListV1Beta1` models were not being generated. Will fix this shortly.

**Comment by tintoy** [comment]
The models are now present but there isn't a client for the `Ingress` API yet. I'll try to set aside some time this weekend to add one and I'll let you know when it's done :)

**Comment by tintoy** [comment]
Sorry for the delay - work's been a little crazy. Will get this done today!

**Comment by tintoy** [comment]
Ok - I've added the client, would you mind trying it out for me to see if it works for you?

```
KubeClient client;

IngressV1Beta1 ingress = await client.IngressesV1Beta1().GetByName("my-ingress");
```

You can install version `2.2.11-unstable0003` from the following MyGet feed:

https://www.myget.org/F/dotnet-kube-client/api/v3/index.json

**Comment by MichaelJCompton** [comment]
Sorry, also took me a few days to get back to this.

Looks like it's working fine for me.

Thanks!
