### ISSUE TITLE
ReplicaControllers also respond replicasets?

### ISSUE THREAD

**Issue by Disturbing** [tintoy/dotnet-kube-client#8]

**Comment by tintoy** [comment]
Hi - do you mean the client also needs to expose the ReplicaSets API?

**Comment by Disturbing** [comment]
Yes, that's correct - looking to see if the replicasets API can be exposed?

**Comment by tintoy** [comment]
Yep, sure - can do, give me 2 mins :)

**Comment by Disturbing** [comment]
Awesome - awaiting for it - if you can push this hotfix to NUGET - you've got kinthub's love for life. <3

**Comment by tintoy** [comment]
If I can push a new build of the packages to a MyGet feed (https://www.myget.org/feed/Packages/dotnet-kube-client) would you be willing to try it out for me?

If you're happy with it, I'll publish the new version to NuGet as well.

**Comment by tintoy** [comment]
Ok, I've published new packages (version is `2.0.0-unstable0066`) to the feed at https://www.myget.org/feed/Packages/dotnet-kube-client - let me know if you have problems accessing it or don't have time to try it out.

**Comment by Disturbing** [comment]
I was able to access unstable0066 - Integrating it and testing today. Should have a response (at least an update) in the next 6-9 hours on my end.

Thanks for moving quickly on this - looking forward to sharing the results.

**Comment by tintoy** [comment]
BTW, I've tried this out myself and it works for me so hopefully it'll do what you want :)

```csharp
using KubeClient;
using KubeClient.Extensions.KubeConfig.Models;
using KubeClient.Models;

Config config = Config.Load(new FileInfo(
    Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
        ".kube",
        "config"
    )
));

KubeClientOptions clientOptions = config.ToKubeClientOptions(defaultKubeNamespace: "kube-system");
using (KubeApiClient client = KubeApiClient.Create(clientOptions))
{
    List<ReplicaSetV1Beta1> replicaSets = await client.ReplicaSetsV1Beta1().List();
    
    Log.Information("Found {ReplicaSetCount} ReplicaSets.", replicaSets.Count);

    foreach (ReplicaSetV1Beta1 replicaSet in replicaSets)
        Log.Information("ReplicaSet: {@ReplicaSet}", replicaSet);
}
```

(you can skip the KubeConfig stuff if you're not getting your connection settings `~/.kube/config`)

**Comment by Disturbing** [comment]
Unfortunately blocked by something else in my env. Will post a comment
hopefully monday on its success :)

**Comment by tintoy** [comment]
Hi @Disturbing - have you had a chance to try this out? Did it work for you?
