### ISSUE TITLE
Accessing cluster Events (kubectl get events)

### ISSUE THREAD

**Issue by brobichaud** [tintoy/dotnet-kube-client#84]
I'm trying to find the way to access cluster events through the api and am unable to find the right starting point. The kubectl command I'm trying to replicate is this:

`kubectl get event --field-selector involvedObject.name=mypodname-69bb65fc5c-slt69`

I'm sure I'm missing something obvious, if you could lead me in the right direction...

**Comment by tintoy** [comment]
A good starting point might be https://github.com/tintoy/dotnet-kube-client#working-out-what-apis-to-call - can you try this out and see what APIs it's calling to do that?

**Comment by brobichaud** [comment]
Yeah I did in fact do that (from your previous advice!), and it's calling:

`/api/v1/namespaces/default/events?fieldSelector=involvedObject.name%3Dmypodname-69bb65fc5c-slt69&limit=500`

But I'm stuck on how to map that to an object in the api.

**Comment by tintoy** [comment]
I'm guessing it's probably [this](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#watch-293). There's no `KubeResourceClient` currently implemented for this API but I don't imagine it would be particularly difficult to do. The only tricky part may be discriminator-based deserialisation of the event data (different events would have different `KubeObjectV1`-derived models as their body.

**Comment by tintoy** [comment]
I did experiment with a custom JsonConverter before but I can't remember where it got up to. Let me have a look.

**Comment by brobichaud** [comment]
Yeah, looks like you've found the right api. And looks like I couldn't find the object because it isn't there! Back to the drawing board. ;-)

**Comment by tintoy** [comment]
Hmm, can't find the JsonConverter (might be hidden on a branch somewhere). I might need to think about what the API for this would look like because it needs a set of k8s model types to be able to deserialise based on `kind`/`apiVersion`. It's totally doable, but so far we haven't needed to maintain a registry of model types. I take it you don't know ahead of time which models you'll need for deserialisation?

**Comment by tintoy** [comment]
FWIW, we already have a [model](https://github.com/tintoy/dotnet-kube-client/blob/develop/src/KubeClient/Models/ResourceEventV1.cs) for this, just not a `JsonConverter` that can handle it.

**Comment by brobichaud** [comment]
Indeed I don't know. As you may have guessed based on my questions over the last few months, I am slowly picking away at some of the core parts of the k8s dashboard that I want to show in our own UI which is tailored to just the parts of k8s that we use. So I may be stretching things for you a bit, my apologies!

**Comment by tintoy** [comment]
Not at all - I think this is the best way to grow a client; when actual requirements arise, otherwise it's just guessing :)

Let me have a think about it for a day or so? I'll see what I can come up with.

**Comment by tintoy** [comment]
I think I may have added some metadata caching (that could be reused / extended) as part of the dynamic API support used by PSKubectl, but I'll have to check.

**Comment by tintoy** [comment]
Ah, so at least the initial part of this can be reused:

https://github.com/tintoy/dotnet-kube-client/blob/6f00774cd785957eb4fb8f20421be9ae757f0830/src/KubeClient/Models/ModelMetadata.cs

**Comment by tintoy** [comment]
Ok - about to add IEventClientV1.

It looks like K8s events are a little complex, mind you, but this might be helpful:

https://lairdnelson.wordpress.com/2017/04/27/kubernetes-events-can-be-complicated/amp/

**Comment by tintoy** [comment]
Ok - I think these changes will do what you need. Could you take a look at #85 and let me know what you think?

**Comment by brobichaud** [comment]
These changes look to be the right direction from my end. But I'd be better able to tell if I could try them out. Could you pull a build together that would let me try them?

**Comment by tintoy** [comment]
There is a [MyGet feed](https://github.com/tintoy/dotnet-kube-client/blob/develop/README.md#packages) where packages from CI builds are published. Could you try using that?

**Comment by tintoy** [comment]
You’re after version `2.3.0-dynamic-resource0053` of each package.

**Comment by brobichaud** [comment]
Yeah this will work nicely! Sweet. :-)

I'm not able to get labelSelectors to work, but I wonder if Events really support that? I'm getting nothing back from EventsV1().List("label=selector");

**Comment by tintoy** [comment]
Hmm - according to the [API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#list-291), it should support that. But I suspect the issue may be that while ALL resources support label selectors, events are not labelled?

**Comment by brobichaud** [comment]
Mmm, yeah if I drill into the events on my cluster I am not seeing the Labels. There is a label array within Metadata but it seems to always be empty.

**Comment by brobichaud** [comment]
So I am good with these changes, thanks a TON!

What does it take in your process to get a mainstream release of this code?

**Comment by tintoy** [comment]
Not much, I can do it this afternoon (it's 10am here in AU) if that suits. Just need to merge to `master` (and tag it once the build / publish succeeds) :)

**Comment by tintoy** [comment]
Sorry, took longer to start this than I’d have liked - about to do it now :)

**Comment by brobichaud** [comment]
I'm still not seeing the expected 2.2.14 build, am I missing something?

**Comment by tintoy** [comment]
Ugh, bloody GitVersion. Sometimes it doesn't increment the version as it should so the build failed when publishing to NuGet.

I've explicitly tagged the version and restarted [the build](https://travis-ci.org/tintoy/dotnet-kube-client/builds/544363817).

**Comment by brobichaud** [comment]
Got it and all builds fine. Thanks so much for being so responsive to ideas and changes! You set the standard for github repo management!

**Comment by tintoy** [comment]
Thanks!
