### ISSUE TITLE
YamlDotNet 6.0.0 

### ISSUE THREAD

**Issue by jonstelly** [tintoy/dotnet-kube-client#91]
YamlDotNet seems to have an API break from 5.X to 6.0, and GitVersionCore released their 5.0.0 release a few days ago, which bumped their dependency to YamlDotNet 6.1.2.  I have a dependency on GitVersionCore and KubeClient and KubeClient is giving an error like this when initializing:

```
System.MissingMethodException: Method not found: 'YamlDotNet.Serialization.Deserializer YamlDotNet.Serialization.DeserializerBuilder.Build()'.
```

Any objections to bumping the YamlDotNet dependency to 6.1.2?  I can submit a PR tomorrow if that's agreeable.

**Comment by tintoy** [comment]
Published [v2.3.0](https://github.com/tintoy/dotnet-kube-client/releases/tag/v2.3.0).

May take a while for the new packages to be indexed by NuGet.
